### ISSUE TITLE
Example makes windows dragging very slow

### ISSUE THREAD

**Issue by killkrt** [tomaka/vulkano#252] opened 2016-09-08 11:12 UTC
Hi,

I've found a strange behavior running the _teapot_ and _triangle_ examples.

One of my CPUs goes always at 100% (taken from the running example) and dragging windows (any windows on the screen) it's quite _hard_, since the mouse seems to be stucked as you try to drag a window, while it is fluid when just moving around.
It's not even possible to close the example window, the only way is pressing <kbd>CTRL</kbd>+<kbd>C</kbd>.

This issue doesn't happen with _image_ example.

Just for info in both cases the output of the example is:
`Using device: GTX 970 (type: DiscreteGpu)`

System info:
OS: Arch Linux (Kernel 4.7.2 64bit)
Video Card: nVidia GTX 970Ti (driver 370.23-4)
Desktop environment: Budgie Dekstop
Wayland: no

**Comment by tomaka** [comment] 2016-09-08 13:10
If the problem is that the CPU goes to 100%, then it can be fixed by forcing the `Fifo` present mode (instead of the first mode available, like the examples do).

Using Fifo means that you won't be able to call `acquire_next_image` more than once every 16.7ms, which means that the thread will sleep a little bit.

**Comment by nphyx** [comment] 2016-09-10 21:09
I solved this by building a frame limiter around the main loop (https://gist.github.com/nphyx/e5970f20c1ce761a0a03276810bcefc4). Does Fifo present mode do this automatically?

**Comment by tomaka** [comment] 2016-09-11 06:34
@nphyx Yes, but if the framerate goes below 60fps it will also reduce the speed of your simulation. This is not always what you want.

**Comment by nphyx** [comment] 2016-09-11 06:41
You could run the render loop in a separate thread from the simulation though, right? Unless you need it synced to the FPS for some reason (I guess some things would make more sense that way). Are there any other disadvantages to the Fifo approach or is it generally the "right" way to manage framerates? And if so, is there a way to set a different framerate?

**Comment by tomaka** [comment] 2016-09-11 06:52
> You could run the render loop in a separate thread from the simulation though, right? Unless you need it synced to the FPS for some reason

Usually the simulation writes to some state which is then read by the rendering system. If you put the two on two separate threads, there are two possibilities: 
- either you lock the whole state and you don't gain anything from multithreading
- or you use fine-grained synchronization and your rendering will often show a partially-updated state.

The "correct" approach, I think, is to maintain a count of the number of times the logic should have been run based on a timer, and a count of the number of times it has been run. Thanks to this you can run the simulation multiple times per frame if the framerate is too low.

> Are there any other disadvantages to the Fifo approach or is it generally the "right" way to manage framerates?

Except `Immediate`, which will show tearing, there's no "wrong way".
Mailbox will make the framerate be as fast as possible and without tearing.
Fifo will block at the nearest divider of 60 (so it will block either at 60fps, 30fps, 20fps, 15fps, etc.).
Relaxed will block at 60fps, but if it goes below it will not round down (ie. it can run at 55fps for example).

It may seem that Relaxed is always better than Fifo, but it also means that the framerate is less stable. With Fifo, the whole range from 30 to 59 will be rounded down to 30. In first person shooter, I think it's usually better to have a stable framerate more than a high framerate.

**Comment by tomaka** [comment] 2017-06-03 14:40
Triage.
Eventually the examples should be changed to use Fifo by default, as it is supposed to guaranteed to be supported by the implementation. Older versions of Mesa didn't support it though, so fixing this problem may break the examples on these old versions.

**Closed** 2017-06-11 18:44 UTC
Labels: experience: easy, status: workable, type: enhancement
